version: "3.8"
services:
  frontend:
    build: ./frontend
    container_name: swasthya-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - ./app/node_modules
    stdin_open: true
    tty: true