name: Feature Request
description: Help us reach newer heights!
labels: ["feature"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!

  - type: textarea
    id: current-behaviour
    attributes:
      label: Current Behaviour
      description: What should we improve?
      placeholder: Dropdown has 5 options, but no way to do X task.
    validations:
      required: true

  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behaviour
      description: How can we improve it?
      placeholder: Add 6th option to dropdown which does X task.

  - type: dropdown
    id: browsers
    attributes:
      label: Which browser do you use?
      multiple: true
      options:
        - Google Chrome
        - Microsoft Edge
        - Safari
        - Firefox
        - Opera
        - Other

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Anything else that you want to share?
      placeholder: The change suggested is important because...

  - type: radio
    id: type-of-feature
    attributes:
      label: Type of Feature
      description: We wanna know more!
      default: new
      options:
        - existing: Is your feature request a part of an existing Issue?
        - new: Is your feature request a new implementation?

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/McTechie/Swasthya/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/McTechie/Swasthya/blob/main/CONTRIBUTING.md)
      options:
        - label: I agree to follow this project's Code of Conduct and Contributing Guidelines
          required: true